apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  annotations:
    classclaims.services.apps.tanzu.vmware.com/xrd-name: xrabbitmqclusters.bitnami.messaging.tanzu.vmware.com
  finalizers:
  - classclaims.services.apps.tanzu.vmware.com/provision-finalizer
  name: rmq1
spec:
  classRef:
    name: rabbitmq-unmanaged
  parameters: {}
